arxlang/irx

README.md
src/arxir/builders/llvmir.py
src/arxir/builders/symbol_table.py

* ```...```
This PR is a:
About this PR:
```
```

refactor: Improve the register handling

---

.github/workflows/main.yaml
.pre-commit-config.yaml
poetry.lock
pyproject.toml
src/arxir/ast/__init__.py
src/arxir/builders/llvmir.py

* ```...```
This PR is a:
About this PR:
```
```

chore: Add ruff to pre-commit

---

.pre-commit-config.yaml
pyproject.toml
src/arxir/ast/__init__.py
src/arxir/ast/blocks.py
src/arxir/builders/base.py
src/arxir/builders/llvmir.py
src/arxir/builders/symbol_table.py
tests/test_module.py

* ```...```
This PR is a:
About this PR:
```
```

chore(pre-commit): Add ruff isort to pre-commit

---

.github/workflows/release.yaml
README.md
docs/index.md
pyproject.toml

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix: Fix documentation publishing

---

docs/installation.md

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix: fix installation step

---

.github/workflows/docs.yaml
.github/workflows/main.yaml
conda/ci.yaml
conda/dev.yaml
conda/release.yaml

- `...`
This PR is a:
About this PR:
complexity.
```
```

chore(ci): Add support for MacOS

---

.makim.yaml

- `...`
This PR is a:
About this PR:
complexity.
```
```

tests: Add code coverage test

---

src/irx/builders/llvmliteir.py
tests/test_for_loops.py

This PR implements support for unary increment/decrement operators (++/--) and fixes critical issues in comparison operators and loop control flow. 
poetry run pytest -k test_for_loops.py    
- `...`
This PR is a:
About this PR:
complexity.
```
```

Implementation of test for ForCount

---

src/irx/builders/symbol_table.py
tests/test_symbol.py

This PR adds test cases to symbol_table.py file .
#38 
run the command  `poetry run pytest -k test_symbol.py`
- `...`
This PR is a:
About this PR:
complexity.
```
```

Add test cases for `symbol_table.py`

---

.makim.yaml
poetry.lock
pyproject.toml
src/irx/builders/base.py
src/irx/builders/llvmliteir.py
src/irx/builders/symbol_table.py
src/irx/tools/__init__.py
src/irx/tools/typing.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

feat: Add support for runtime type check

---

tests/data/test_unary_op.ll
tests/test_unary_op.py

The test checks the correct handling of unary operations on integer variables, ensuring proper evaluation and combination of these operations within the ASTx framework. 
#54 
- `...`
This PR is a:
About this PR:
complexity.
```
```

tests:Add test for unaryOp

---

src/irx/builders/llvmliteir.py
src/irx/system.py
tests/test_if_stmt.py

This PR adds tests and debugs ifStmt function further increasing test coverage .
Ensures that the merged block after if-else always terminates correctly by modifying the test case to include an explicit return statement.Instead of emitting ret inside the visit(IfStmt) method (which could limit flexibility), I chose to append a FunctionReturn node in the test.
Solve #48 
run `pytest`
This PR is a:
About this PR:
complexity.
Increases test coverage to 85%
```
```

test:add tests for ifStmt

---

.makim.yaml
pyproject.toml
src/irx/builders/base.py
tests/conftest.py
tests/test_binary_op.py
tests/test_unary_op.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

tests: improve tests for building and running the binary from astx nodes

---

src/irx/builders/llvmliteir.py
tests/test_fibonacci.py
tests/test_variableAssignment.py
tests/test_while.py

This PR adds translation for WhileStmt and its tests.
- `...`
This PR is a:
About this PR:
complexity.
```
```

Add translation for `WhileStmt`

---

tests/test_fibonacci.py
tests/test_variable_assignment.py

Renames the file to snake_case
- `...`
This PR is a:
About this PR:
complexity.
```
```

Renaming the file to snake_case

---

src/irx/builders/llvmliteir.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix: Fix typing with clang

---

src/irx/builders/llvmliteir.py
src/irx/system.py
tests/test_cast.py

This PR adds explicit casting, inorder to use PrintExpr with integers.
- `...`
This PR is a:
About this PR:
complexity.
```
```

Add casting to use printexpr with integers

---

pyproject.toml
src/irx/builders/llvmliteir.py
tests/test_boolean.py

This PR adds support for boolean datatype
#24
- `...`
This PR is a:
About this PR:
complexity.
```
```

Add support for boolean

---

.makim.yaml
src/irx/builders/base.py
src/irx/builders/llvmliteir.py
tests/conftest.py
tests/test_binary_op.py
tests/test_boolean.py
tests/test_cast.py
tests/test_fibonacci.py
tests/test_float.py
tests/test_variable_assignment.py

This PR adds support for float16 datatype
- `...`
This PR is a:
About this PR:
complexity.
```
```

add support for float32

---

src/irx/builders/llvmliteir.py

This PR adds support for float16 
- `...`
This PR is a:
About this PR:
complexity.
```
```

add support for float16

---

conda/ci.yaml
conda/dev.yaml
conda/release.yaml
poetry.lock
pyproject.toml

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix: Update ASTx to version 0.23.0

---

.github/workflows/reviewer-pr.yaml

- `...`
This PR is a:
About this PR:
complexity.
```
```

chore(ci): Update Reviewer Action to 1.0.5

---

README.md
docs/index.md

- `...`
This PR is a:
About this PR:
complexity.
```
```

docs: Improve README.md

---

.github/workflows/reviewer-pr.yaml

- `...`
This PR is a:
About this PR:
complexity.
```
```

chore(ci): Update GHA Reviewer to 1.0.8

---

.github/workflows/reviewer-pr.yaml

- `...`
This PR is a:
About this PR:
complexity.
```
```

chore(ci): Update GHA Reviewer to version 1.0.12

---

.github/workflows/reviewer-pr.yaml

- `...`
This PR is a:
About this PR:
complexity.
```
```

chore(ci): Update GHA Reviewer to 1.0.14

---

.github/workflows/reviewer-pr.yaml

- `...`
This PR is a:
About this PR:
complexity.
```
```

chore(ci): Update GHA Reviewer to 1.0.15

---

.github/workflows/reviewer-pr.yaml

- `...`
This PR is a:
About this PR:
complexity.
```
```

chore(ci): Update GHA Reviewer to v1.1.0
